#!/usr/bin/env bash

error(){ echo -e "❌ $@" >&2 && return 0 ; } 

error_exit(){ error "$@"; exit 1; }

BANDIT_SERVER='bandit.labs.overthewire.org'
BANDIT_PORT='2220'
BANDIT_PASSWORDS="${HOME}/.local/etc/ssh_bandit/passwords"

if [[ ${BASH_SOURCE[0]} == ${0} ]]; then 

    set -euo pipefail

    if ! command -v sshpass &>/dev/null
    then error "'sshpass' is not installed. Please install it first."
         if [[ $OSTYPE == darwin* ]]
         then echo 'Run: brew install sshpass'
         else echo 'Run: sudo apt install sshpass'
         fi
    fi

    level="$1"
    user="bandit${level}"
    
    if [[ -z $level || ! $level =~ ^[0-9]+$ ]]
    then error_exit "Usage: ssh_bandit <level_number>"
    fi
    
    pw=$(sed -n "$((level + 1))p" "$BANDIT_PASSWORDS")
    
    if [[ -z $pw ]]
    then error_exit "❌ No password found for bandit${level}"
    fi
    
    eval "pw=$pw"
    if [[ -f $pw ]]
    then ssh -t -i "$pw" \
             -p "$BANDIT_PORT" "${user}@${BANDIT_SERVER}" "${@:2}"
    else sshpass -p "$pw" ssh -t \
             -p "$BANDIT_PORT" "${user}@${BANDIT_SERVER}" "${@:2}"
    fi
fi
